### ISSUE TITLE
demo website not able to connect to the backend due to CORS

### ISSUE THREAD

**Issue by shivamdev-lgtm** [amazingshellyyy/startkicker#2]
I visited your demo website for this project at https://amazingshellyyy.com/startkicker/ but I am not able to login/sign up. In the developer console it is throwing this CORS related error: 

`Access to XMLHttpRequest at 'https://startkicker.amazingshellyyy.com/api/v1/auth/signup' from origin 'https://amazingshellyyy.com' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

**Comment by amazingshellyyy** [comment]
Thanks for discovering that. I haven't been maintaining the website for some time. 
The CORS issue is fixed!
